version: '3'


services:
    reverseproxy:
        image: nginx:7
        ports:
            - 80:8080


        restart: always

    jboss1:
        depends_on:
            - reverseproxy
        image: jboss-war:latest
        restart: always

    jboss2:
        depends_on:
            - reverseproxy
        image: jboss-war:latest
        restart: always
